#
#  Author: Hari Sekhon
#  Date: 2020-02-04 21:39:47 +0000 (Tue, 04 Feb 2020)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/harisekhon/pylib
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

name: CI Mac

env:
  DEBUG: 1

on:
  push:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 10 30 * *'

jobs:
  build:
    #name: build
    timeout-minutes: 10
    strategy:
      matrix:
        os: [macos-latest]
        #python-version: [2.7, 3.6, 3.7, 3.8, pypy2, pypy3]
        python-version: [2.7, 3.6]
    steps:
    - uses: actions/checkout@v2
#   - uses: actions/cache@v1
#     with:
#       path: ~/Library/Caches/pip
#       key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
#       restore-keys: |
#         ${{ runner.os }}-pip-
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: build & test
      run: make build test
