#
#  Author: Hari Sekhon
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/pylib
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                                  F l a k e 8
# ============================================================================ #

# Lint any Python code found in the repo

---
name: Flake8

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - main
    paths:
      - '**/*.py'
      - .github/workflows/flake8.yaml
  pull_request:
    branches:
      - master
      - main
    paths:
      - '**/*.py'
      - .github/workflows/flake8.yaml
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

jobs:
  flake8:
    uses: HariSekhon/GitHub-Actions/.github/workflows/flake8.yaml@master
