#
#  Author: Hari Sekhon
#  Date: 2020-02-04 21:40:04 +0000 (Tue, 04 Feb 2020)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/harisekhon/pylib
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

name: PyPy 3

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

jobs:
  build:
    name: PyPy3
    uses: HariSekhon/GitHub-Actions/.github/workflows/pypy3.yaml@master
    #with:
    #  debug: 1
