#
#  Author: Hari Sekhon
#  Date: 2020-02-04 21:40:04 +0000 (Tue, 04 Feb 2020)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/pylib
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

---
name: Python 3.9

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.pl'
      - '**/*.rb'
      - '**/*.go'
      - '**/*.sh'
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 7 * * *'

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.repository.fork == false
    name: Python 3.9
    uses: HariSekhon/GitHub-Actions/.github/workflows/python.yaml@master
    with:
      version: 3.9
      debug: ${{ github.event.inputs.debug }}
