#
#  Author: Hari Sekhon
#  Date: 2020-02-04 21:40:04 +0000 (Tue, 04 Feb 2020)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/pylib
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

---
name: Python 3.8

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false  # build auto-cancellation - enabling this causes false-positive badge failure statuses

jobs:
  build:
    name: Python 3.8
    uses: HariSekhon/GitHub-Actions/.github/workflows/python.yaml@master
    with:
      version: 3.8
      #debug: 1
